<a href="https://colab.research.google.com/github/sys-frOSt/Pytorch_pipeline_practice/blob/main/training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/sys-frOSt/Pytorch_pipeline_practice.git

Cloning into 'Pytorch_pipeline_practice'...
warning: You appear to have cloned an empty repository.

In [ ]:
%cd /content/Pytorch_pipeline_practice

/content/Pytorch_pipeline_practice

In [ ]:
!git config --global user.email "aviraj1234.dum@gmail.com"
!git config --global user.name "frost"

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch

In [ ]:

df = pd.read_csv(
    "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
)

df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df

    diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0           M        17.99  ...          0.4601                  0.11890
1           M        20.57  ...          0.2750                  0.08902
2           M        19.69  ...          0.3613                  0.08758
3           M        11.42  ...          0.6638                  0.17300
4           M        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564         M        21.56  ...          0.2060                  0.07115
565         M        20.13  ...          0.2572                  0.06637
566         M        16.60  ...          0.2218                  0.07820
567         M        20.60  ...          0.4087                  0.12400
568         B         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [ ]:
X_train,X_test,y_test,y_train=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train

array([[-0.46204859, -0.48346359, -0.46663056, ..., -0.13580377,
         0.21788029, -0.42044774],
       [ 0.26739683, -0.08011976,  0.22242656, ..., -0.03482178,
        -0.99994532, -0.80958745],
       [ 0.13451337, -1.31994369,  0.10068357, ..., -0.33837064,
        -0.44359471, -0.75784893],
       ...,
       [-0.83525323, -1.45286382, -0.85932344, ..., -0.893018  ,
        -0.06676421, -0.90976203],
       [-0.36592012, -1.45744727, -0.4321982 , ..., -1.1215086 ,
        -1.80697716, -0.60868788],
       [ 0.94877803,  4.55145911,  0.88401978, ...,  1.39098368,
        -0.076468  ,  0.03914442]])

In [ ]:
y_test

497    B
514    M
513    B
336    B
189    B
      ..
568    B
84     B
153    B
179    B
239    M
Name: diagnosis, Length: 455, dtype: object

LABEL ENCODING THE CLASSES

In [ ]:
encode=LabelEncoder()
y_train=encode.fit_transform(y_train)
y_test=encode.transform(y_test)

COVERSIOON NUMPY ARRAYS TO TENSORS

In [ ]:
X_test_tensor=torch.from_numpy(X_test)
X_train_tensor=torch.from_numpy(X_train)
y_test_tensor=torch.from_numpy(y_test)
y_train_tensor=torch.from_numpy(y_train)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

MAKING THE NEURAL NETWORK

In [ ]:
class my_simple_nn:
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

    #forward pass
  def forward(self,X):
    #matrix multiplication
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
#loss calculation
  def loss(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [ ]:
learning_rate=0.1
epoch=25

pipeline

In [ ]:

#trainingn pipline
model=my_simple_nn(X_train_tensor)
#dfine loops
for epoch in range(epoch):
  #forward pass
  y_pred=model.forward(X_train_tensor)
  #print(y_pred)

  #calculate loss
  loss=model.loss(y_pred,y_train_tensor)
  #print(f"epoch:{epoch+1},loss:{loss.item()}")

  #backward pass
  loss.backward()


  #parametres update
  with torch.no_grad():#for not tracking the weights
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

    #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f"epoch:{epoch+1},loss:{loss.item()}")

epoch:1,loss:3.3862246421354487
epoch:2,loss:3.2528373007344396
epoch:3,loss:3.119862155260173
epoch:4,loss:2.98379186669639
epoch:5,loss:2.845764339091925
epoch:6,loss:2.7053633563803263
epoch:7,loss:2.5619747089564493
epoch:8,loss:2.4205868519841265
epoch:9,loss:2.2759400324427017
epoch:10,loss:2.1275733475550256
epoch:11,loss:1.9837234689134373
epoch:12,loss:1.84486373641677
epoch:13,loss:1.712409758163148
epoch:14,loss:1.5903567210866456
epoch:15,loss:1.476057468211853
epoch:16,loss:1.3697125976610043
epoch:17,loss:1.2762604847043424
epoch:18,loss:1.1953485920055356
epoch:19,loss:1.1261526080314415
epoch:20,loss:1.06751168890039
epoch:21,loss:1.0180528983502655
epoch:22,loss:0.9763374162197994
epoch:23,loss:0.941010933636786
epoch:24,loss:0.91089950124946
epoch:25,loss:0.8850369743197468

In [ ]:
model.bias

tensor([-0.2058], dtype=torch.float64, requires_grad=True)

In [ ]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.4
          ).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy:{accuracy.item()}")

accuracy:0.5278195738792419

In [ ]:
!git add .

In [ ]:
!git commit -m "first commit"
!git push origin main

On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/sys-frOSt/Pytorch_pipeline_practice.git'