<a href="https://colab.research.google.com/github/sys-frOSt/Pytorch_prac/blob/main/training_pipepline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn

In [3]:

df = pd.read_csv(
    "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
)

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2)

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [9]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [10]:
X_train

array([[-1.5523046 , -1.11381224, -1.54629048, ..., -1.75360824,
        -0.51408407, -0.31527528],
       [-0.47499762, -0.65495485, -0.37512387, ...,  0.28296842,
         0.49416836,  1.05530183],
       [ 1.72864963,  1.11492362,  2.13157636, ...,  2.05245305,
         3.9796607 ,  0.84850528],
       ...,
       [-0.35241439,  2.27377262, -0.38954204, ..., -0.76825114,
        -0.86121323, -0.64856972],
       [ 0.24909863,  1.40288004,  0.14763744, ..., -1.31366519,
        -2.13454611, -1.60445376],
       [-1.81200998,  1.24836684, -1.81405632, ..., -1.75360824,
        -0.07386118, -0.76021785]])

In [11]:
X_train_tensor=torch.from_numpy(X_train.astype(np.float32))
X_test_tensor=torch.from_numpy(X_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
      out=self.linear(features)
      out=self.sigmoid(out)
      return out

In [17]:
#loss function
loss_fuction=nn.BCELoss()

In [18]:
learning_rate=0.1
num_epochs=200

In [ ]:
model=Model(X_train_tensor.shape[1])
#start the loop
for epoch in range(num_epochs):
  #initalize the forward pass
  y_pred=model(X_train_tensor)
  #loss calculate
  loss=loss_fuction(y_pred,y_train_tensor.view
  )
  #backpass
  loss.backward()

  #update parameter
  with torch.no_grad():
    model.linear.weight-=learning_rate*model.linear.weight.grad
    model.linear.bias-=learning_rate*model.linear.bias.grad

  #after updating the parameters, the weight will turn into zero for another loop
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #printing the each epoch
  print(f"epoch:{epoch+1},loss:{loss.item()}")

In [26]:
model=Model(X_train_tensor.shape[1])
#optim using
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

#start the loop
for epoch in range(num_epochs):

  #initalize the forward pass
  y_pred=model(X_train_tensor)

  #loss calculate
  loss=loss_fuction(y_pred,y_train_tensor.view(-1,1))

  #clearing gradients
  optimizer.zero_grad()

  #backpass
  loss.backward()

  #update the optimizer using optim
  optimizer.step()

  #printing the each epoch
  print(f"epoch:{epoch+1},loss:{loss.item()}")

epoch:1,loss:0.7805880308151245
epoch:2,loss:0.5638691186904907
epoch:3,loss:0.4562239348888397
epoch:4,loss:0.39367732405662537
epoch:5,loss:0.3521234393119812
epoch:6,loss:0.3220447599887848
epoch:7,loss:0.2989872395992279
epoch:8,loss:0.28057777881622314
epoch:9,loss:0.2654278874397278
epoch:10,loss:0.2526664137840271
epoch:11,loss:0.24171671271324158
epoch:12,loss:0.23218028247356415
epoch:13,loss:0.22377215325832367
epoch:14,loss:0.21628248691558838
epoch:15,loss:0.20955294370651245
epoch:16,loss:0.20346160233020782
epoch:17,loss:0.19791279733181
epoch:18,loss:0.19283024966716766
epoch:19,loss:0.18815238773822784
epoch:20,loss:0.18382874131202698
epoch:21,loss:0.17981745302677155
epoch:22,loss:0.17608359456062317
epoch:23,loss:0.17259757220745087
epoch:24,loss:0.169334277510643
epoch:25,loss:0.16627199947834015
epoch:26,loss:0.16339200735092163
epoch:27,loss:0.16067790985107422
epoch:28,loss:0.1581154316663742
epoch:29,loss:0.15569187700748444
epoch:30,loss:0.15339604020118713
epoch:31,loss:0.15121783316135406
epoch:32,loss:0.1491483747959137
epoch:33,loss:0.14717954397201538
epoch:34,loss:0.14530405402183533
epoch:35,loss:0.14351531863212585
epoch:36,loss:0.14180731773376465
epoch:37,loss:0.14017464220523834
epoch:38,loss:0.138612300157547
epoch:39,loss:0.1371157318353653
epoch:40,loss:0.13568075001239777
epoch:41,loss:0.1343035250902176
epoch:42,loss:0.1329805552959442
epoch:43,loss:0.1317085474729538
epoch:44,loss:0.13048452138900757
epoch:45,loss:0.12930570542812347
epoch:46,loss:0.12816953659057617
epoch:47,loss:0.12707366049289703
epoch:48,loss:0.12601585686206818
epoch:49,loss:0.12499404698610306
epoch:50,loss:0.12400636821985245
epoch:51,loss:0.12305101752281189
epoch:52,loss:0.12212638556957245
epoch:53,loss:0.12123089283704758
epoch:54,loss:0.12036308646202087
epoch:55,loss:0.11952165514230728
epoch:56,loss:0.11870534718036652
epoch:57,loss:0.11791294068098068
epoch:58,loss:0.11714334785938263
epoch:59,loss:0.11639553308486938
epoch:60,loss:0.11566853523254395
epoch:61,loss:0.11496139317750931
epoch:62,loss:0.11427327990531921
epoch:63,loss:0.1136033684015274
epoch:64,loss:0.1129508689045906
epoch:65,loss:0.1123151034116745
epoch:66,loss:0.11169534176588058
epoch:67,loss:0.11109094321727753
epoch:68,loss:0.11050134152173996
epoch:69,loss:0.10992591083049774
epoch:70,loss:0.1093640998005867
epoch:71,loss:0.10881542414426804
epoch:72,loss:0.10827935487031937
epoch:73,loss:0.10775543749332428
epoch:74,loss:0.10724322497844696
epoch:75,loss:0.10674230754375458
epoch:76,loss:0.10625225305557251
epoch:77,loss:0.1057727038860321
epoch:78,loss:0.10530326515436172
epoch:79,loss:0.10484364628791809
epoch:80,loss:0.10439345240592957
epoch:81,loss:0.10395240038633347
epoch:82,loss:0.10352017730474472
epoch:83,loss:0.10309651494026184
epoch:84,loss:0.10268110036849976
epoch:85,loss:0.10227371007204056
epoch:86,loss:0.10187403857707977
epoch:87,loss:0.10148190706968307
epoch:88,loss:0.10109703242778778
epoch:89,loss:0.10071924328804016
epoch:90,loss:0.10034826397895813
epoch:91,loss:0.09998394548892975
epoch:92,loss:0.09962605684995651
epoch:93,loss:0.09927443414926529
epoch:94,loss:0.09892889857292175
epoch:95,loss:0.09858925640583038
epoch:96,loss:0.09825535118579865
epoch:97,loss:0.0979270190000534
epoch:98,loss:0.09760412573814392
epoch:99,loss:0.09728650003671646
epoch:100,loss:0.09697400778532028
epoch:101,loss:0.09666649997234344
epoch:102,loss:0.096363864839077
epoch:103,loss:0.0960659608244896
epoch:104,loss:0.09577266871929169
epoch:105,loss:0.09548388421535492
epoch:106,loss:0.09519945830106735
epoch:107,loss:0.09491930902004242
epoch:108,loss:0.09464333206415176
epoch:109,loss:0.09437141567468643
epoch:110,loss:0.09410344064235687
epoch:111,loss:0.09383934736251831
epoch:112,loss:0.09357902407646179
epoch:113,loss:0.09332237392663956
epoch:114,loss:0.09306932985782623
epoch:115,loss:0.09281979501247406
epoch:116,loss:0.09257367253303528
epoch:117,loss:0.0923309177160263
epoch:118,loss:0.09209141880273819
epoch:119,loss:0.09185514599084854
epoch:120,loss:0.091621994972229
epoch:121,loss:0.0913918986916542
epoch:122,loss:0.09116479754447937
epoch:123,loss:0.09094061702489853
epoch:124,loss:0.0907193049788475
epoch:125,loss:0.09050080180168152
epoch:126,loss:0.0902850404381752
epoch:127,loss:0.09007196128368378
epoch:128,loss:0.08986150473356247
epoch:129,loss:0.0896536335349083
epoch:130,loss:0.08944828808307648
epoch:131,loss:0.08924540132284164
epoch:132,loss:0.08904494345188141
epoch:133,loss:0.0888468474149704
epoch:134,loss:0.08865109086036682
epoch:135,loss:0.0884576067328453
epoch:136,loss:0.08826635032892227
epoch:137,loss:0.08807728439569473
epoch:138,loss:0.0878903791308403
epoch:139,loss:0.0877055898308754
epoch:140,loss:0.08752285689115524
epoch:141,loss:0.08734215795993805
epoch:142,loss:0.08716344833374023
epoch:143,loss:0.08698668330907822
epoch:144,loss:0.0868118479847908
epoch:145,loss:0.08663886785507202
epoch:146,loss:0.08646776527166367
epoch:147,loss:0.08629848062992096
epoch:148,loss:0.08613097667694092
epoch:149,loss:0.08596520870923996
epoch:150,loss:0.08580116182565689
epoch:151,loss:0.08563881367444992
epoch:152,loss:0.08547813445329666
epoch:153,loss:0.08531907945871353
epoch:154,loss:0.08516163378953934
epoch:155,loss:0.0850057527422905
epoch:156,loss:0.08485142886638641
epoch:157,loss:0.0846986323595047
epoch:158,loss:0.08454733341932297
epoch:159,loss:0.08439750224351883
epoch:160,loss:0.08424912393093109
epoch:161,loss:0.08410217612981796
epoch:162,loss:0.08395662158727646
epoch:163,loss:0.08381246030330658
epoch:164,loss:0.08366964012384415
epoch:165,loss:0.08352816849946976
epoch:166,loss:0.08338802307844162
epoch:167,loss:0.08324915170669556
epoch:168,loss:0.08311156183481216
epoch:169,loss:0.08297522366046906
epoch:170,loss:0.08284012228250504
epoch:171,loss:0.08270625025033951
epoch:172,loss:0.0825735554099083
epoch:173,loss:0.08244205266237259
epoch:174,loss:0.08231171220541
epoch:175,loss:0.08218251168727875
epoch:176,loss:0.08205442875623703
epoch:177,loss:0.08192747086286545
epoch:178,loss:0.08180161565542221
epoch:179,loss:0.08167682588100433
epoch:180,loss:0.08155309408903122
epoch:181,loss:0.08143042773008347
epoch:182,loss:0.08130878955125809
epoch:183,loss:0.0811881572008133
epoch:184,loss:0.08106853812932968
epoch:185,loss:0.08094990253448486
epoch:186,loss:0.08083225041627884
epoch:187,loss:0.08071555197238922
epoch:188,loss:0.08059980720281601
epoch:189,loss:0.08048500120639801
epoch:190,loss:0.08037111908197403
epoch:191,loss:0.08025814592838287
epoch:192,loss:0.08014606684446335
epoch:193,loss:0.08003488183021545
epoch:194,loss:0.07992454618215561
epoch:195,loss:0.0798150971531868
epoch:196,loss:0.07970649003982544
epoch:197,loss:0.07959873229265213
epoch:198,loss:0.07949179410934448
epoch:199,loss:0.0793856680393219
epoch:200,loss:0.07928036153316498

In [79]:
model.linear.bias

Parameter containing:
tensor([-0.1574], requires_grad=True)

In [27]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5
          ).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy:{accuracy.item()}")

accuracy:0.5236995816230774